name: IoT Data Pipeline

on:
  # schedule:
  #   - cron: '0 1 * * *' # รันตอน 01:00 UTC (ตรงกับ 08:00 น. เวลาไทย)
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install pandas sqlalchemy psycopg2-binary

      - name: Run Python Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: python push_data.py
